FROM maven:3.8.1-openjdk-17 as Build
COPY . .
RUN mvn package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=Build /target/TeacherCRUD-0.0.1-SNAPSHOT.jar TeacherCRUD.jar
EXPOSE 8089
ENTRYPOINT [ "java","-jar","TeacherCRUD.jar"]

